### ISSUE TITLE
Ignoring reboot because of chroot

### ISSUE THREAD

**Issue by ghost** [sigboe/GPD-Arch-LUKS-LVM#14]
I follow the guide step-by-step but at the final step (after installing kde) and trying to reboot I receive the following message:
`running in chroot, ignoring request `

I would add to the guide the moment where to press CTRL + D in order to exit the chroot mode.

**Comment by sigboe** [comment]
Thanks for the feedback, my bad, I thought it was not needed, but you are right.

Edited the guide per your suggestion.
